from __future__ import annotations

ADMIN_TABLE_COLUMNS = [
    "ranking_global",
    "ranking_por_cultivo",
    "parcela_id",
    "cultivo",
    "estado_evaluacion",
    "prioridad_visual",
    "prioridad",
    "prioridad_score",
    "riesgo_actual",
    "riesgo_operativo_5d",
    "riesgo_operativo_10d",
    "delta_operativo_10d",
    "riesgo_pred_5d",
    "riesgo_pred_10d",
    "delta_10d",
    "tendencia_reciente_5d",
    "fecha_lectura",
    "dias_desde_lectura",
    "ndmi_mean",
    "msi_mean",
    "confianza_lectura",
    "outlier_especial",
    "score_suavizado",
    "riesgo_actual_suavizado",
    "prioridad_score_suavizado",
    "outlier_espacial",
    "tipo_outlier_espacial",
    "persistencia_temporal",
    "diagnostico_outlier",
    "neighbor_riesgo_actual_median",
    "riesgo_actual_vs_neighbor_median",
    "historial_reciente_count",
    "riesgo_reciente_weighted_mean",
    "riesgo_vs_reciente_weighted_mean",
    "motivo_ruido",
    "severidad_ruido",
    "accion_recomendada",
    "outlier_count_30d",
    "persistente_count_30d",
    "ruido_count_30d",
    "ultima_fecha_outlier",
    "ultima_fecha_persistente",
    "ultima_fecha_ruido",
]

CLIENT_TABLE_COLUMNS = [
    "parcela_id",
    "cultivo",
    "estado_evaluacion",
    "prioridad_visual",
    "riesgo_actual",
    "riesgo_operativo_5d",
    "riesgo_operativo_10d",
    "delta_operativo_10d",
    "tendencia_reciente_5d",
    "fecha_lectura",
    "dias_desde_lectura",
    "confianza_lectura",
]

CLIENT_FORBIDDEN_COLUMNS = {
    "riesgo_pred_5d",
    "riesgo_pred_10d",
    "delta_5d",
    "delta_10d",
    "outlier_espacial",
    "tipo_outlier_espacial",
    "persistencia_temporal",
    "diagnostico_outlier",
    "motivo_ruido",
    "severidad_ruido",
    "accion_recomendada",
    "confianza_motivo",
    "outlier_especial",
    "score_suavizado",
    "riesgo_actual_suavizado",
    "prioridad_score_suavizado",
    "neighbor_riesgo_actual_median",
    "riesgo_actual_vs_neighbor_median",
    "riesgo_vs_reciente_weighted_mean",
}

COLUMN_LABELS = {
    "ranking_global": "Ranking",
    "ranking_por_cultivo": "Ranking cultivo",
    "parcela_id": "Parcela",
    "cultivo": "Cultivo",
    "estado_evaluacion": "Estado evaluación",
    "prioridad_visual": "Prioridad",
    "prioridad": "Prioridad modelo",
    "prioridad_score": "Score",
    "riesgo_actual": "Riesgo actual",
    "riesgo_pred_5d": "Predicción 5 días",
    "riesgo_pred_10d": "Predicción 10 días",
    "delta_10d": "Delta 10 días",
    "riesgo_operativo_5d": "Proyección 5 días",
    "riesgo_operativo_10d": "Proyección 10 días",
    "delta_operativo_10d": "Cambio proyectado 10 días",
    "tendencia_reciente_5d": "Tendencia reciente",
    "fecha_lectura": "Fecha lectura",
    "dias_desde_lectura": "Días desde lectura",
    "ndmi_mean": "NDMI",
    "msi_mean": "MSI",
    "confianza_lectura": "Confianza",
    "outlier_especial": "Outlier especial",
    "score_suavizado": "Score suavizado",
    "riesgo_actual_suavizado": "Riesgo suavizado",
    "prioridad_score_suavizado": "Score operativo",
    "outlier_espacial": "Outlier espacial",
    "tipo_outlier_espacial": "Tipo outlier",
    "persistencia_temporal": "Persistencia temporal",
    "diagnostico_outlier": "Diagnóstico",
    "neighbor_riesgo_actual_median": "Mediana vecinal",
    "riesgo_actual_vs_neighbor_median": "Diferencia vecinal",
    "historial_reciente_count": "Historial reciente",
    "riesgo_reciente_weighted_mean": "Riesgo reciente ponderado",
    "riesgo_vs_reciente_weighted_mean": "Diferencia contra reciente",
    "motivo_ruido": "Motivo técnico",
    "severidad_ruido": "Severidad",
    "accion_recomendada": "Criterio técnico",
    "outlier_count_30d": "Outliers 30d",
    "persistente_count_30d": "Persistentes 30d",
    "ruido_count_30d": "Ruido 30d",
    "ultima_fecha_outlier": "Último outlier",
    "ultima_fecha_persistente": "Último persistente",
    "ultima_fecha_ruido": "Último ruido",
}


def table_columns(admin_mode: bool, available_columns: list[str] | set[str]) -> list[str]:
    available = set(available_columns)
    source = ADMIN_TABLE_COLUMNS if admin_mode else CLIENT_TABLE_COLUMNS
    return [col for col in source if col in available]


def column_labels(columns: list[str]) -> dict[str, str]:
    return {col: COLUMN_LABELS[col] for col in columns if col in COLUMN_LABELS}
